project:
  type: website

website:
  title: "Liyve's Notes"
  site-url: "https://Liyvew.github.io/Mathematics-Notes-Repository/"
  navbar:
    title: "Liyve's Notes"
    left:
      - href: index.qmd
        text: Overview
      - text: Algebra
        menu:
          - href: en-commutative-algebra.qmd
            text: "Commutative Algebra"
      - text: Number Theory
        menu:
          - href: en-pre-classification-quadratic-forms-over-q.qmd
            text: "Classification of Quadratic Forms over ℚ"
      - text: Probability
        menu:
          - href: en-regular-conditional-probability.qmd
            text: "Regular Conditional Probability (EN)"
          - href: cn-regular-conditional-probability.qmd
            text: "正则条件概率 (中文)"
    right:
      - icon: github
        href: https://github.com/Liyvew/Mathematics-Notes-Repository